[package]
name = "chapter01"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }



[dependencies]
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

log = "0.4"
env_logger = "0.9"